language: python

python:
  - "3.8"

services:
    - postgresql

addons:
  postgresql: "11"
  apt:
    packages:
    - postgresql-11
    - postgresql-client-11
env:
  global:
  - PGPORT=5433
  - PGUSER=travis

before_install:
  - sudo sed -i -e "/local.*peer/s/postgres/all/" -e "s/peer\|md5/trust/g" /etc/postgresql/*/main/pg_hba.conf
  - postgres --version
  - sudo pg_ctlcluster 11 main restart

install:
   - pip install -r requirements.txt

before_script:
  - sleep 15
  - psql -c 'create database soh_test2;' -U postgres

after_script:
  - coveralls

script:
  #Secret_Key
  - export $DJANGO_SECRET_KEY

  # Run Black formatter
  - black --check .

  # Run Flake8 linter
  - flake8 --extend-ignore E501,F401,F811,E711,F541,E722,E265,E266,F841,E402
  
  # Run Django tests
  - coverage run manage.py test


deploy:
  provider: elasticbeanstalk
  access_key_id: $ACCESS_KEY_ID
  secret_access_key: $ACCESS_KEY
  region: "us-east-1"
  app: "ShowOfHands"
  env: "ShowofHands-dev"
  bucket_name: "elasticbeanstalk-us-east-1-754415205510"
  bucket_path: "ShowofHands/"
  on:
    repo: gcivil-nyu-org/INET-Wednesday-Spring2023-Team-2
    branch: develop